package com.partha.adminApplication.constants;

public interface SQLConstant {
	
	public static final String INVENTORY_EXPORT_QUERY = "SELECT ID , TITLE , AUTHOR , PUBLISHER , PUBLICATIONDATE , LANGUAGE , PAGES , FORMAT , ISBN , AVAILABLEUNITS FROM BOOKS WHERE ACTIVE=TRUE";
	
	public static final String MONTHLY_SALES_REPORT_QUERY = " SELECT     MONTH(M.INSERTDATE) AS MNO , COUNT(*)  AS RECORDCOUNT  ,  MONTHNAME(M.INSERTDATE)  MNAME"+
			" FROM ORDERMASTER M "+
			" WHERE YEAR(M.INSERTDATE) = :year "+
			" GROUP BY MONTH(M.INSERTDATE), MONTHNAME(M.INSERTDATE) ";

}
